Thu Sep 05 23:45:13 CEST 2013 : Apache Derby Server di rete: 10.8.1.2 - (1095077) avviato e pronto ad accettare connessioni sulla porta 1527
----------------------------------------------------------------
Thu Sep 05 23:45:25 CEST 2013:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.8.1.2 - (1095077): istanza a816c00e-0140-f016-1357-fffff95d4cfb
su directory database D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB\ProvaDB1  con caricatore classi sun.misc.Launcher$AppClassLoader@5b2f9ee1 

java.vendor=Oracle Corporation
java.runtime.version=1.7.0_25-b17
user.dir=C:\Program Files\glassfish-3.1.2.2\javadb
derby.system.home=D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB
Programma di caricamento classe database avviato - derby.database.classpath=''
----------------------------------------------------------------
Thu Sep 05 23:45:26 CEST 2013:
Arresto istanza a816c00e-0140-f016-1357-fffff95d4cfb con caricatore classi D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB\ProvaDB1 
Thu Sep 05 23:45:26 CEST 2013 Thread[DRDAConnThread_4,5,main] (DATABASE = ProvaDB1), (DRDAID = {2}), Arresto database 'ProvaDB1'.
----------------------------------------------------------------
Thu Sep 05 23:45:26 CEST 2013:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.8.1.2 - (1095077): istanza a13ec033-0140-f016-1357-fffff95d4cfb
su directory database D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB\ProvaDB1  con caricatore classi sun.misc.Launcher$AppClassLoader@5b2f9ee1 

java.vendor=Oracle Corporation
java.runtime.version=1.7.0_25-b17
user.dir=C:\Program Files\glassfish-3.1.2.2\javadb
derby.system.home=D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB
Programma di caricamento classe database avviato - derby.database.classpath=''
----------------------------------------------------------------
Thu Sep 05 23:46:20 CEST 2013:
Arresto istanza a13ec033-0140-f016-1357-fffff95d4cfb con caricatore classi D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB\ProvaDB1 
Thu Sep 05 23:46:20 CEST 2013 Thread[DRDAConnThread_6,5,main] (DATABASE = ProvaDB1), (DRDAID = {6}), Arresto database 'ProvaDB1'.
Thu Sep 05 23:46:20 CEST 2013 Thread[DRDAConnThread_6,5,main] Cleanup action starting
java.sql.SQLException: Database 'ProvaDB1' non trovato.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Database 'ProvaDB1' non trovato.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'ProvaDB1' non trovato.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Sep 05 23:46:20 CEST 2013 Thread[DRDAConnThread_6,5,main] (DATABASE = ProvaDB1), (DRDAID = {7}), Database 'ProvaDB1' non trovato.
Thu Sep 05 23:46:20 CEST 2013 Thread[DRDAConnThread_6,5,main] Cleanup action starting
java.sql.SQLException: Database 'ProvaDB1' non trovato.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Database 'ProvaDB1' non trovato.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'ProvaDB1' non trovato.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Sep 05 23:46:20 CEST 2013 Thread[DRDAConnThread_6,5,main] (DATABASE = ProvaDB1), (DRDAID = {8}), Database 'ProvaDB1' non trovato.
----------------------------------------------------------------
Thu Sep 05 23:55:09 CEST 2013:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.8.1.2 - (1095077): istanza 29d8c03e-0140-f016-1357-fffff95d4cfb
su directory database D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB\ProvaDB1  con caricatore classi sun.misc.Launcher$AppClassLoader@5b2f9ee1 

java.vendor=Oracle Corporation
java.runtime.version=1.7.0_25-b17
user.dir=C:\Program Files\glassfish-3.1.2.2\javadb
derby.system.home=D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB
Programma di caricamento classe database avviato - derby.database.classpath=''
----------------------------------------------------------------
Thu Sep 05 23:56:14 CEST 2013:
Arresto istanza 29d8c03e-0140-f016-1357-fffff95d4cfb con caricatore classi D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB\ProvaDB1 
Thu Sep 05 23:56:14 CEST 2013 Thread[DRDAConnThread_3,5,main] (DATABASE = ProvaDB1), (DRDAID = {14}), Arresto database 'ProvaDB1'.
----------------------------------------------------------------
Thu Sep 05 23:56:14 CEST 2013:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.8.1.2 - (1095077): istanza 295dc08b-0140-f016-1357-fffff95d4cfb
su directory database D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB\ProvaDB1  con caricatore classi sun.misc.Launcher$AppClassLoader@5b2f9ee1 

java.vendor=Oracle Corporation
java.runtime.version=1.7.0_25-b17
user.dir=C:\Program Files\glassfish-3.1.2.2\javadb
derby.system.home=D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB
Programma di caricamento classe database avviato - derby.database.classpath=''
----------------------------------------------------------------
Thu Sep 05 23:56:36 CEST 2013:
Arresto istanza 295dc08b-0140-f016-1357-fffff95d4cfb con caricatore classi D:\Giulio\UniVe\TAW\NetBeansProjects\WebApplication1\DB\ProvaDB1 
Thu Sep 05 23:56:36 CEST 2013 Thread[DRDAConnThread_7,5,main] (DATABASE = ProvaDB1), (DRDAID = {16}), Arresto database 'ProvaDB1'.
----------------------------------------------------------------
Fri Sep 06 00:01:34 CEST 2013: Shutting down Derby engine
----------------------------------------------------------------
